apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::211478333253:role/eksctl-simple-jwt-app-nodegroup-si-NodeInstanceRole-jU6xuuzT1kLn
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    - userarn: arn:aws:iam::211478333253:server-deployment-and-containe-CodeBuildServiceRole-wzzFTiIjz4Vv
      groups:
        - system:masters
kind: ConfigMap
metadata:
  creationTimestamp: "2024-11-20T06:57:52Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "5482"
  uid: 14ad1bfb-d9b6-4b7e-894c-8188bfc03832
