apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::211478333253:role/eksctl-flask-app-service-nodegroup-NodeInstanceRole-4NcdrF1ajqG3
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::211478333253:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"mapRoles":"- groups:\n  - system:bootstrappers\n  - system:nodes\n  rolearn: arn:aws:iam::211478333253:role/eksctl-flask-app-service-nodegroup-NodeInstanceRole-4NcdrF1ajqG3\n  username: system:node:{{EC2PrivateDNSName}}\n- groups:\n  - system:masters\n  rolearn: arn:aws:iam::211478333253:role/UdacityFlaskDeployCBKubectlRole\n  username: build\n"},"kind":"ConfigMap","metadata":{"annotations":{},"creationTimestamp":"2024-11-18T08:12:06Z","name":"aws-auth","namespace":"kube-system","resourceVersion":"2689","uid":"ada5fc21-bcd1-4da2-a911-0d020f8eb61d"}}
  creationTimestamp: "2024-11-18T08:12:06Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "8093"
  uid: ada5fc21-bcd1-4da2-a911-0d020f8eb61d
